language: sh
dist:     trusty
sudo:     false
install:
  - git clone git://github.com/rylnd/shpec        --branch 0.2.2      --depth 1 "$HOME"/shpec
  - git clone git://github.com/binaryphile/kaizen --branch v10.11.11  --depth 1 "$TRAVIS_BUILD_DIR"/../kaizen
  - git clone git://github.com/binaryphile/sorta  --branch v11.10.11  --depth 1 "$TRAVIS_BUILD_DIR"/../sorta
  - export PATH=$HOME/shpec/bin:$TRAVIS_BUILD_DIR/lib:$TRAVIS_BUILD_DIR/../kaizen/lib:$TRAVIS_BUILD_DIR/../sorta/lib:$PATH
script:   ./all-shpecs
git:
  depth:  1
